-- MySQL Workbench Synchronization
-- Generated: 2015-05-20 23:40
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: vyadav

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS reunited.system_variables;
DROP TABLE IF EXISTS reunited.user_pin_history;
DROP TABLE IF EXISTS reunited.role;
DROP TABLE IF EXISTS reunited.timetable;
DROP TABLE IF EXISTS reunited.period;
DROP TABLE IF EXISTS reunited.test_result;
DROP TABLE IF EXISTS reunited.test;
DROP TABLE IF EXISTS reunited.relation_session_student;
DROP TABLE IF EXISTS reunited.relation_parent_student;
DROP TABLE IF EXISTS reunited.session;
DROP TABLE IF EXISTS reunited.user;
DROP TABLE IF EXISTS reunited.class;
DROP TABLE IF EXISTS reunited.branch;
DROP TABLE IF EXISTS reunited.address;
DROP TABLE IF EXISTS reunited.institute;
DROP TABLE IF EXISTS reunited.code;
DROP TABLE IF EXISTS reunited.code_type;

CREATE TABLE IF NOT EXISTS `reunited`.`CODE_TYPE` (
  `CODE_TYPE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CODE_TYPE_NAME` VARCHAR(4) NOT NULL,
  `CODE_TYPE_SHORT_DESC` VARCHAR(10) NOT NULL,
  `CODE_TYPE_DESC` VARCHAR(45) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CODE_TYPE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `reunited`.`CODE` (
  `CODE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CODE_CODE_TYPE_ID` INT(11) NOT NULL,
  `CODE_NAME` VARCHAR(4) NOT NULL,
  `CODE_SHORT_DESC` VARCHAR(10) NOT NULL,
  `CODE_DESC` VARCHAR(45) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CODE_ID`),
  INDEX `FK_CODE_1_idx` (`CODE_CODE_TYPE_ID` ASC),
  CONSTRAINT `FK_CODE_1`
    FOREIGN KEY (`CODE_CODE_TYPE_ID`)
    REFERENCES `reunited`.`CODE_TYPE` (`CODE_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`ADDRESS` (
  `ADDRESS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS_P_LINE_1` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS_P_LINE_2` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS_P_LINE_3` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS_P_CITY` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_P_DISTRICT` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_P_POSTCODE` VARCHAR(10) NULL DEFAULT NULL,
  `ADDRESS_P_STATE` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_P_COUNTRY` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_C_LINE_1` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS_C_LINE_2` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS_C_LINE_3` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS_C_CITY` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_C_DISTRICT` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_C_POSTCODE` VARCHAR(10) NULL DEFAULT NULL,
  `ADDRESS_C_STATE` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_C_COUNTRY` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS_LAND_CODE` INT(11) NULL DEFAULT NULL,
  `ADDRESS_MOBILE_1_CODE` INT(11) NULL DEFAULT NULL,
  `ADDRESS_MOBILE_1_NUMBER` INT(11) NULL DEFAULT NULL,
  `ADDRESS_MOBILE_2_CODE` INT(11) NULL DEFAULT NULL,
  `ADDRESS_MOBILE_2_NUMBER` INT(11) NULL DEFAULT NULL,
  `ADDRESS_FAX` INT(11) NULL DEFAULT NULL,
  `ADDRESS_EMAIL_1` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS_EMAIL_2` VARCHAR(45) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ADDRESS_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`SYSTEM_VARIABLES` (
  `SYSTEM_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SYSTEM_CURRENT_SESSION_YEAR` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`SYSTEM_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`INSTITUTE` (
  `INSTITUTE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `INSTITUTE_NAME` VARCHAR(50) NOT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`INSTITUTE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`BRANCH` (
  `BRANCH_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BRANCH_INSTITUTE_ID` INT(11) NOT NULL,
  `BRANCH_NAME` VARCHAR(45) NOT NULL,
  `BRANCH_ADDRESS_ID` INT(11) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`BRANCH_ID`),
  INDEX `FK_BRANCH_1_idx` (`BRANCH_INSTITUTE_ID` ASC),
  INDEX `FK_BRANCH_2_idx` (`BRANCH_ADDRESS_ID` ASC),
  CONSTRAINT `FK_BRANCH_1`
    FOREIGN KEY (`BRANCH_INSTITUTE_ID`)
    REFERENCES reunited.`INSTITUTE` (`INSTITUTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BRANCH_2`
    FOREIGN KEY (`BRANCH_ADDRESS_ID`)
    REFERENCES reunited.`ADDRESS` (`ADDRESS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`RELATION_PARENT_STUDENT` (
  `RELATION_PS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RELATION_PS_PARENT_ID` INT(11) NOT NULL,
  `RELATION_PS_STUDENT_ID` INT(11) NOT NULL,
  `RELATION_PS_TYPE` INT(11) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`RELATION_PS_ID`),
  INDEX `FK_RELATION_PARENT_STUDENT_3_idx` (`RELATION_PS_TYPE` ASC),
  INDEX `FK_RELATION_PARENT_STUDENT_1_idx` (`RELATION_PS_PARENT_ID` ASC),
  INDEX `FK_RELATION_PARENT_STUDENT_2_idx` (`RELATION_PS_STUDENT_ID` ASC),
  CONSTRAINT `FK_RELATION_PARENT_STUDENT_1`
    FOREIGN KEY (`RELATION_PS_PARENT_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RELATION_PARENT_STUDENT_2`
    FOREIGN KEY (`RELATION_PS_STUDENT_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RELATION_PARENT_STUDENT_3`
    FOREIGN KEY (`RELATION_PS_TYPE`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`USER` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_LOGIN_ID` VARCHAR(45) NOT NULL,
  `USER_EMAIL_ADDRESS` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Can be used for login instead of login id',
  `USER_TYPE` INT(11) NOT NULL COMMENT 'parent, student or staff',
  `USER_STATUS` INT(11) NULL DEFAULT NULL,
  `USER_BRANCH_ID` INT(11) NULL DEFAULT NULL,
  `USER_REGISTRATION_ID` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Will be null for parent',
  `USER_JOINING_DATE` DATE NULL DEFAULT NULL COMMENT 'Will be null for parent',
  `USER_TENURE_END_DATE` DATE NULL DEFAULT NULL,
  `USER_SEX` CHAR(1) NULL DEFAULT NULL,
  `USER_FIRST_NAME` VARCHAR(20) NULL DEFAULT NULL,
  `USER_MIDDLE_NAME` VARCHAR(20) NULL DEFAULT NULL,
  `USER_SURNAME` VARCHAR(20) NULL DEFAULT NULL,
  `USER_DOB` DATE NULL DEFAULT NULL,
  `USER_ADDRESS_ID` INT(11) NULL DEFAULT NULL,
  `USER_AUTH_TYPE` INT(11) NULL DEFAULT NULL COMMENT 'Authentication can be done outside the system.',
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  INDEX `FK_USER_1_idx` (`USER_TYPE` ASC),
  INDEX `FK_USER_2_idx` (`USER_AUTH_TYPE` ASC),
  INDEX `FK_USER_3_idx` (`USER_STATUS` ASC),
  INDEX `FK_USER_4_idx` (`USER_ADDRESS_ID` ASC),
  INDEX `FK_USER_5_idx` (`USER_BRANCH_ID` ASC),
  CONSTRAINT `FK_USER_1`
    FOREIGN KEY (`USER_TYPE`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_2`
    FOREIGN KEY (`USER_AUTH_TYPE`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_3`
    FOREIGN KEY (`USER_STATUS`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_4`
    FOREIGN KEY (`USER_ADDRESS_ID`)
    REFERENCES reunited.`ADDRESS` (`ADDRESS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_5`
    FOREIGN KEY (`USER_BRANCH_ID`)
    REFERENCES reunited.`BRANCH` (`BRANCH_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`USER_PIN_HISTORY` (
  `USER_PIN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_PIN_USER_ID` INT(11) NOT NULL,
  `USER_PIN_NUMBER` VARCHAR(256) NOT NULL,
  `USER_PIN_VIOLATION_COUNT` INT(11) NULL DEFAULT 0,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`USER_PIN_ID`),
  INDEX `FK_USER_PIN_HISTORY_1_idx` (`USER_PIN_USER_ID` ASC),
  CONSTRAINT `FK_USER_PIN_HISTORY_1`
    FOREIGN KEY (`USER_PIN_USER_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`CLASS` (
  `CLASS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CLASS_BRANCH_ID` INT(11) NOT NULL,
  `CLASS_NAME_ID` INT(11) NOT NULL,
  `CLASS_SECTION_ID` INT(11) NOT NULL,
  PRIMARY KEY (`CLASS_ID`),
  INDEX `FK_CLASS_1_idx` (`CLASS_BRANCH_ID` ASC),
  INDEX `FK_CLASS_2_idx` (`CLASS_NAME_ID` ASC),
  INDEX `FK_CLASS_3_idx` (`CLASS_SECTION_ID` ASC),
  CONSTRAINT `FK_CLASS_1`
    FOREIGN KEY (`CLASS_BRANCH_ID`)
    REFERENCES reunited.`BRANCH` (`BRANCH_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CLASS_2`
    FOREIGN KEY (`CLASS_NAME_ID`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CLASS_3`
    FOREIGN KEY (`CLASS_SECTION_ID`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`SESSION` (
  `SESSION_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SESSION_CLASS_ID` INT(11) NOT NULL,
  `SESSION_YEAR` VARCHAR(4) NOT NULL,
  `SESSION_NAME` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Eg: 2015_10_A\n',
  `SESSION_STREAM_TYPE` INT(11) NULL DEFAULT NULL COMMENT 'Medical, Arts, etc\n',
  `SESSION_CLASS_TEACHER_ID` INT(11) NULL DEFAULT NULL,
  `SESSION_CLASS_ROOM_NUMBER` VARCHAR(10) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`SESSION_ID`),
  INDEX `FK_SESSION_1_idx` (`SESSION_CLASS_ID` ASC),
  INDEX `FK_SESSION_2_idx` (`SESSION_STREAM_TYPE` ASC),
  INDEX `FK_SESSION_3_idx` (`SESSION_CLASS_TEACHER_ID` ASC),
  CONSTRAINT `FK_SESSION_1`
    FOREIGN KEY (`SESSION_CLASS_ID`)
    REFERENCES reunited.`CLASS` (`CLASS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SESSION_2`
    FOREIGN KEY (`SESSION_STREAM_TYPE`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SESSION_3`
    FOREIGN KEY (`SESSION_CLASS_TEACHER_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`RELATION_SESSION_STUDENT` (
  `RELATION_SS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RELATION_SS_SESSION_ID` INT(11) NOT NULL,
  `RELATION_SS_STUDENT_ID` INT(11) NOT NULL,
  `RELATION_SS_ROLL_NO` INT(11) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`RELATION_SS_ID`),
  INDEX `FK_RELATION_SESSION_STUDENT_1_idx` (`RELATION_SS_SESSION_ID` ASC),
  INDEX `FK_RELATION_SESSION_STUDENT_2_idx` (`RELATION_SS_STUDENT_ID` ASC),
  CONSTRAINT `FK_RELATION_SESSION_STUDENT_1`
    FOREIGN KEY (`RELATION_SS_SESSION_ID`)
    REFERENCES reunited.`SESSION` (`SESSION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RELATION_SESSION_STUDENT_2`
    FOREIGN KEY (`RELATION_SS_STUDENT_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`TIMETABLE` (
  `TIMETABLE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TIMETABLE_SESSION_ID` INT(11) NOT NULL,
  `TIMETABLE_SUBJECT_ID` INT(11) NOT NULL,
  `TIMETABLE_PERIOD_ID` INT(11) NOT NULL,
  `TIMETABLE_DAY_OF_WEEK` INT(11) NOT NULL,
  `TIMETABLE_EFFECTIVE_FROM` DATE NOT NULL,
  `TIMETABLE_TEACHER_ID` INT(11) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`TIMETABLE_ID`),
  INDEX `FK_TIMETABLE_2_idx` (`TIMETABLE_SUBJECT_ID` ASC),
  UNIQUE INDEX `UK_TIMETABLE_1` (`TIMETABLE_SESSION_ID` ASC, `TIMETABLE_PERIOD_ID` ASC, `TIMETABLE_DAY_OF_WEEK` ASC, `TIMETABLE_EFFECTIVE_FROM` ASC),
  INDEX `FK_TIMETABLE_4_idx` (`TIMETABLE_PERIOD_ID` ASC),
  INDEX `FK_TIMETABLE_3_idx` (`TIMETABLE_TEACHER_ID` ASC),
  CONSTRAINT `FK_TIMETABLE_1`
    FOREIGN KEY (`TIMETABLE_SESSION_ID`)
    REFERENCES reunited.`SESSION` (`SESSION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TIMETABLE_2`
    FOREIGN KEY (`TIMETABLE_SUBJECT_ID`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TIMETABLE_3`
    FOREIGN KEY (`TIMETABLE_TEACHER_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TIMETABLE_4`
    FOREIGN KEY (`TIMETABLE_PERIOD_ID`)
    REFERENCES reunited.`PERIOD` (`PERIOD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`PERIOD` (
  `PERIOD_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PERIOD_NAME` VARCHAR(10) NOT NULL,
  `PERIOD_FROM_TIME` TIME NULL DEFAULT NULL,
  `PERIOD_TO_TIME` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`PERIOD_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`TEST` (
  `TEST_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TEST_SESSION_ID` INT(11) NOT NULL,
  `TEST_SUBJECT_ID` INT(11) NOT NULL,
  `TEST_TYPE` INT(11) NOT NULL,
  `TEST_HIGHEST_MARKS` INT(11) NOT NULL,
  `TEST_DATE` DATE NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`TEST_ID`),
  INDEX `FK_TEST_1_idx` (`TEST_SESSION_ID` ASC),
  INDEX `FK_TEST_2_idx` (`TEST_SUBJECT_ID` ASC),
  INDEX `FK_TEST_3_idx` (`TEST_TYPE` ASC),
  CONSTRAINT `FK_TEST_1`
    FOREIGN KEY (`TEST_SESSION_ID`)
    REFERENCES reunited.`SESSION` (`SESSION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TEST_2`
    FOREIGN KEY (`TEST_SUBJECT_ID`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TEST_3`
    FOREIGN KEY (`TEST_TYPE`)
    REFERENCES reunited.`CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`TEST_RESULT` (
  `TEST_RESULT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TEST_RESULT_TEST_ID` INT(11) NOT NULL,
  `TEST_RESULT_STUDENT_ID` INT(11) NOT NULL,
  `TEST_RESULT_MARKS_OBTAINED` INT(11) NOT NULL DEFAULT 0,
  `TEST_RESULT_REMARKS` VARCHAR(45) NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`TEST_RESULT_ID`),
  INDEX `FK_TEST_RESULT_1_idx` (`TEST_RESULT_TEST_ID` ASC),
  INDEX `FK_TEST_RESULT_2_idx` (`TEST_RESULT_STUDENT_ID` ASC),
  CONSTRAINT `FK_TEST_RESULT_1`
    FOREIGN KEY (`TEST_RESULT_TEST_ID`)
    REFERENCES reunited.`TEST` (`TEST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TEST_RESULT_2`
    FOREIGN KEY (`TEST_RESULT_STUDENT_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`ATTENDENCE` (
  `ATTENDENCE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ATTENDENCE_USER_ID` INT(11) NOT NULL,
  `ATTENDENCE_DATE` DATE NOT NULL,
  `ATTENDENCE_ABSENT_PRESENCE_FH` INT(11) NOT NULL COMMENT 'FIRST HALF. 0 ABSENT, 1 PRESENT',
  `ATTENDENCE_ABSENT_PRESENCE_SH` INT(11) NOT NULL COMMENT 'SECOND HALF. 0 ABSENT, 1 PRESENT',
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ATTENDENCE_ID`),
  INDEX `FK_ATTENDENCE_1_idx` (`ATTENDENCE_USER_ID` ASC),
  CONSTRAINT `FK_ATTENDENCE_1`
    FOREIGN KEY (`ATTENDENCE_USER_ID`)
    REFERENCES reunited.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS reunited.`ROLE` (
  `ROLE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
