package reunited.kickstart.model;

// Generated May 16, 2015 11:25:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "reunited")
public class Student implements java.io.Serializable {

	private Integer id;
	private Integer branchId;
	private String gender;
	private String firstname;
	private String lastname;
	private Date dob;
	private Date joiningdate;
	private Date enddate;
	private Integer addressid;
	private String isuser;
	private String registrationid;

	public Student() {
	}

	public Student(Integer branchId, String gender, String firstname,
			String lastname, Date dob, Date joiningdate, Date enddate,
			Integer addressid, String isuser, String registrationid) {
		this.branchId = branchId;
		this.gender = gender;
		this.firstname = firstname;
		this.lastname = lastname;
		this.dob = dob;
		this.joiningdate = joiningdate;
		this.enddate = enddate;
		this.addressid = addressid;
		this.isuser = isuser;
		this.registrationid = registrationid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "BranchId")
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "Gender", length = 50)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "Firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joiningdate", length = 10)
	public Date getJoiningdate() {
		return this.joiningdate;
	}

	public void setJoiningdate(Date joiningdate) {
		this.joiningdate = joiningdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "addressid")
	public Integer getAddressid() {
		return this.addressid;
	}

	public void setAddressid(Integer addressid) {
		this.addressid = addressid;
	}

	@Column(name = "isuser", length = 50)
	public String getIsuser() {
		return this.isuser;
	}

	public void setIsuser(String isuser) {
		this.isuser = isuser;
	}

	@Column(name = "registrationid", length = 50)
	public String getRegistrationid() {
		return this.registrationid;
	}

	public void setRegistrationid(String registrationid) {
		this.registrationid = registrationid;
	}

}
