package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "reunited")
public class Address extends PersistenceBase implements java.io.Serializable {

	private Integer addressId;
	private String addressPLine1;
	private String addressPLine2;
	private String addressPLine3;
	private String addressPCity;
	private String addressPDistrict;
	private String addressPPostcode;
	private String addressPState;
	private String addressPCountry;
	private String addressCLine1;
	private String addressCLine2;
	private String addressCLine3;
	private String addressCCity;
	private String addressCDistrict;
	private String addressCPostcode;
	private String addressCState;
	private String addressCCountry;
	private Integer addressLandCode;
	private Integer addressMobile1Code;
	private Integer addressMobile1Number;
	private Integer addressMobile2Code;
	private Integer addressMobile2Number;
	private Integer addressFax;
	private String addressEmail1;
	private String addressEmail2;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public Address() {
	}

	public Address(String addressPLine1, String addressPLine2,
			String addressPLine3, String addressPCity, String addressPDistrict,
			String addressPPostcode, String addressPState,
			String addressPCountry, String addressCLine1, String addressCLine2,
			String addressCLine3, String addressCCity, String addressCDistrict,
			String addressCPostcode, String addressCState,
			String addressCCountry, Integer addressLandCode,
			Integer addressMobile1Code, Integer addressMobile1Number,
			Integer addressMobile2Code, Integer addressMobile2Number,
			Integer addressFax, String addressEmail1, String addressEmail2,
			Date lastUpdated, String lastUpdatedBy, Set users, Set branches) {
		this.addressPLine1 = addressPLine1;
		this.addressPLine2 = addressPLine2;
		this.addressPLine3 = addressPLine3;
		this.addressPCity = addressPCity;
		this.addressPDistrict = addressPDistrict;
		this.addressPPostcode = addressPPostcode;
		this.addressPState = addressPState;
		this.addressPCountry = addressPCountry;
		this.addressCLine1 = addressCLine1;
		this.addressCLine2 = addressCLine2;
		this.addressCLine3 = addressCLine3;
		this.addressCCity = addressCCity;
		this.addressCDistrict = addressCDistrict;
		this.addressCPostcode = addressCPostcode;
		this.addressCState = addressCState;
		this.addressCCountry = addressCCountry;
		this.addressLandCode = addressLandCode;
		this.addressMobile1Code = addressMobile1Code;
		this.addressMobile1Number = addressMobile1Number;
		this.addressMobile2Code = addressMobile2Code;
		this.addressMobile2Number = addressMobile2Number;
		this.addressFax = addressFax;
		this.addressEmail1 = addressEmail1;
		this.addressEmail2 = addressEmail2;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ADDRESS_ID", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "ADDRESS_P_LINE_1", length = 45)
	public String getAddressPLine1() {
		return this.addressPLine1;
	}

	public void setAddressPLine1(String addressPLine1) {
		this.addressPLine1 = addressPLine1;
	}

	@Column(name = "ADDRESS_P_LINE_2", length = 45)
	public String getAddressPLine2() {
		return this.addressPLine2;
	}

	public void setAddressPLine2(String addressPLine2) {
		this.addressPLine2 = addressPLine2;
	}

	@Column(name = "ADDRESS_P_LINE_3", length = 45)
	public String getAddressPLine3() {
		return this.addressPLine3;
	}

	public void setAddressPLine3(String addressPLine3) {
		this.addressPLine3 = addressPLine3;
	}

	@Column(name = "ADDRESS_P_CITY", length = 20)
	public String getAddressPCity() {
		return this.addressPCity;
	}

	public void setAddressPCity(String addressPCity) {
		this.addressPCity = addressPCity;
	}

	@Column(name = "ADDRESS_P_DISTRICT", length = 20)
	public String getAddressPDistrict() {
		return this.addressPDistrict;
	}

	public void setAddressPDistrict(String addressPDistrict) {
		this.addressPDistrict = addressPDistrict;
	}

	@Column(name = "ADDRESS_P_POSTCODE", length = 10)
	public String getAddressPPostcode() {
		return this.addressPPostcode;
	}

	public void setAddressPPostcode(String addressPPostcode) {
		this.addressPPostcode = addressPPostcode;
	}

	@Column(name = "ADDRESS_P_STATE", length = 20)
	public String getAddressPState() {
		return this.addressPState;
	}

	public void setAddressPState(String addressPState) {
		this.addressPState = addressPState;
	}

	@Column(name = "ADDRESS_P_COUNTRY", length = 20)
	public String getAddressPCountry() {
		return this.addressPCountry;
	}

	public void setAddressPCountry(String addressPCountry) {
		this.addressPCountry = addressPCountry;
	}

	@Column(name = "ADDRESS_C_LINE_1", length = 45)
	public String getAddressCLine1() {
		return this.addressCLine1;
	}

	public void setAddressCLine1(String addressCLine1) {
		this.addressCLine1 = addressCLine1;
	}

	@Column(name = "ADDRESS_C_LINE_2", length = 45)
	public String getAddressCLine2() {
		return this.addressCLine2;
	}

	public void setAddressCLine2(String addressCLine2) {
		this.addressCLine2 = addressCLine2;
	}

	@Column(name = "ADDRESS_C_LINE_3", length = 45)
	public String getAddressCLine3() {
		return this.addressCLine3;
	}

	public void setAddressCLine3(String addressCLine3) {
		this.addressCLine3 = addressCLine3;
	}

	@Column(name = "ADDRESS_C_CITY", length = 20)
	public String getAddressCCity() {
		return this.addressCCity;
	}

	public void setAddressCCity(String addressCCity) {
		this.addressCCity = addressCCity;
	}

	@Column(name = "ADDRESS_C_DISTRICT", length = 20)
	public String getAddressCDistrict() {
		return this.addressCDistrict;
	}

	public void setAddressCDistrict(String addressCDistrict) {
		this.addressCDistrict = addressCDistrict;
	}

	@Column(name = "ADDRESS_C_POSTCODE", length = 10)
	public String getAddressCPostcode() {
		return this.addressCPostcode;
	}

	public void setAddressCPostcode(String addressCPostcode) {
		this.addressCPostcode = addressCPostcode;
	}

	@Column(name = "ADDRESS_C_STATE", length = 20)
	public String getAddressCState() {
		return this.addressCState;
	}

	public void setAddressCState(String addressCState) {
		this.addressCState = addressCState;
	}

	@Column(name = "ADDRESS_C_COUNTRY", length = 20)
	public String getAddressCCountry() {
		return this.addressCCountry;
	}

	public void setAddressCCountry(String addressCCountry) {
		this.addressCCountry = addressCCountry;
	}

	@Column(name = "ADDRESS_LAND_CODE")
	public Integer getAddressLandCode() {
		return this.addressLandCode;
	}

	public void setAddressLandCode(Integer addressLandCode) {
		this.addressLandCode = addressLandCode;
	}

	@Column(name = "ADDRESS_MOBILE_1_CODE")
	public Integer getAddressMobile1Code() {
		return this.addressMobile1Code;
	}

	public void setAddressMobile1Code(Integer addressMobile1Code) {
		this.addressMobile1Code = addressMobile1Code;
	}

	@Column(name = "ADDRESS_MOBILE_1_NUMBER")
	public Integer getAddressMobile1Number() {
		return this.addressMobile1Number;
	}

	public void setAddressMobile1Number(Integer addressMobile1Number) {
		this.addressMobile1Number = addressMobile1Number;
	}

	@Column(name = "ADDRESS_MOBILE_2_CODE")
	public Integer getAddressMobile2Code() {
		return this.addressMobile2Code;
	}

	public void setAddressMobile2Code(Integer addressMobile2Code) {
		this.addressMobile2Code = addressMobile2Code;
	}

	@Column(name = "ADDRESS_MOBILE_2_NUMBER")
	public Integer getAddressMobile2Number() {
		return this.addressMobile2Number;
	}

	public void setAddressMobile2Number(Integer addressMobile2Number) {
		this.addressMobile2Number = addressMobile2Number;
	}

	@Column(name = "ADDRESS_FAX")
	public Integer getAddressFax() {
		return this.addressFax;
	}

	public void setAddressFax(Integer addressFax) {
		this.addressFax = addressFax;
	}

	@Column(name = "ADDRESS_EMAIL_1", length = 45)
	public String getAddressEmail1() {
		return this.addressEmail1;
	}

	public void setAddressEmail1(String addressEmail1) {
		this.addressEmail1 = addressEmail1;
	}

	@Column(name = "ADDRESS_EMAIL_2", length = 45)
	public String getAddressEmail2() {
		return this.addressEmail2;
	}

	public void setAddressEmail2(String addressEmail2) {
		this.addressEmail2 = addressEmail2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}


}
