package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendence generated by hbm2java
 */
@Entity
@Table(name = "attendence", catalog = "reunited")
public class Attendence implements java.io.Serializable {

	private Integer attendenceId;
	private User user;
	private Date attendenceDate;
	private int attendenceAbsentPresenceFh;
	private int attendenceAbsentPresenceSh;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public Attendence() {
	}

	public Attendence(User user, Date attendenceDate,
			int attendenceAbsentPresenceFh, int attendenceAbsentPresenceSh) {
		this.user = user;
		this.attendenceDate = attendenceDate;
		this.attendenceAbsentPresenceFh = attendenceAbsentPresenceFh;
		this.attendenceAbsentPresenceSh = attendenceAbsentPresenceSh;
	}

	public Attendence(User user, Date attendenceDate,
			int attendenceAbsentPresenceFh, int attendenceAbsentPresenceSh,
			Date lastUpdated, String lastUpdatedBy) {
		this.user = user;
		this.attendenceDate = attendenceDate;
		this.attendenceAbsentPresenceFh = attendenceAbsentPresenceFh;
		this.attendenceAbsentPresenceSh = attendenceAbsentPresenceSh;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ATTENDENCE_ID", unique = true, nullable = false)
	public Integer getAttendenceId() {
		return this.attendenceId;
	}

	public void setAttendenceId(Integer attendenceId) {
		this.attendenceId = attendenceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATTENDENCE_USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ATTENDENCE_DATE", nullable = false, length = 10)
	public Date getAttendenceDate() {
		return this.attendenceDate;
	}

	public void setAttendenceDate(Date attendenceDate) {
		this.attendenceDate = attendenceDate;
	}

	@Column(name = "ATTENDENCE_ABSENT_PRESENCE_FH", nullable = false)
	public int getAttendenceAbsentPresenceFh() {
		return this.attendenceAbsentPresenceFh;
	}

	public void setAttendenceAbsentPresenceFh(int attendenceAbsentPresenceFh) {
		this.attendenceAbsentPresenceFh = attendenceAbsentPresenceFh;
	}

	@Column(name = "ATTENDENCE_ABSENT_PRESENCE_SH", nullable = false)
	public int getAttendenceAbsentPresenceSh() {
		return this.attendenceAbsentPresenceSh;
	}

	public void setAttendenceAbsentPresenceSh(int attendenceAbsentPresenceSh) {
		this.attendenceAbsentPresenceSh = attendenceAbsentPresenceSh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
