package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Class generated by hbm2java
 */
@Entity
@Table(name = "class", catalog = "reunited")
public class Class implements java.io.Serializable {

	private Integer classId;
	private Branch branch;
	private Code codeByClassNameId;
	private Code codeByClassSectionId;

	public Class() {
	}

	public Class(Branch branch, Code codeByClassNameId,
			Code codeByClassSectionId) {
		this.branch = branch;
		this.codeByClassNameId = codeByClassNameId;
		this.codeByClassSectionId = codeByClassSectionId;
	}

	public Class(Branch branch, Code codeByClassNameId,
			Code codeByClassSectionId, Set sessions) {
		this.branch = branch;
		this.codeByClassNameId = codeByClassNameId;
		this.codeByClassSectionId = codeByClassSectionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CLASS_ID", unique = true, nullable = false)
	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLASS_BRANCH_ID", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLASS_NAME_ID", nullable = false)
	public Code getCodeByClassNameId() {
		return this.codeByClassNameId;
	}

	public void setCodeByClassNameId(Code codeByClassNameId) {
		this.codeByClassNameId = codeByClassNameId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLASS_SECTION_ID", nullable = false)
	public Code getCodeByClassSectionId() {
		return this.codeByClassSectionId;
	}

	public void setCodeByClassSectionId(Code codeByClassSectionId) {
		this.codeByClassSectionId = codeByClassSectionId;
	}


}
