package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name = "code", catalog = "reunited")
public class Code implements java.io.Serializable {

	private Integer codeId;
	private CodeType codeType;
	private String codeName;
	private String codeShortDesc;
	private String codeDesc;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public Code() {
	}

	public Code(CodeType codeType, String codeName, String codeShortDesc) {
		this.codeType = codeType;
		this.codeName = codeName;
		this.codeShortDesc = codeShortDesc;
	}

	public Code(CodeType codeType, String codeName, String codeShortDesc,
			String codeDesc, Date lastUpdated, String lastUpdatedBy,
			Set usersForUserAuthType, Set usersForUserStatus,
			Set testsForTestSubjectId, Set testsForTestType, Set timetables,
			Set sessions, Set relationParentStudents, Set usersForUserType,
			Set classesForClassNameId, Set classesForClassSectionId) {
		this.codeType = codeType;
		this.codeName = codeName;
		this.codeShortDesc = codeShortDesc;
		this.codeDesc = codeDesc;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CODE_ID", unique = true, nullable = false)
	public Integer getCodeId() {
		return this.codeId;
	}

	public void setCodeId(Integer codeId) {
		this.codeId = codeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_CODE_TYPE_ID", nullable = false)
	public CodeType getCodeType() {
		return this.codeType;
	}

	public void setCodeType(CodeType codeType) {
		this.codeType = codeType;
	}

	@Column(name = "CODE_NAME", nullable = false, length = 4)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@Column(name = "CODE_SHORT_DESC", nullable = false, length = 10)
	public String getCodeShortDesc() {
		return this.codeShortDesc;
	}

	public void setCodeShortDesc(String codeShortDesc) {
		this.codeShortDesc = codeShortDesc;
	}

	@Column(name = "CODE_DESC", length = 45)
	public String getCodeDesc() {
		return this.codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}



}
