package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CodeType generated by hbm2java
 */
@Entity
@Table(name = "code_type", catalog = "reunited")
public class CodeType implements java.io.Serializable {

	private Integer codeTypeId;
	private String codeTypeName;
	private String codeTypeShortDesc;
	private String codeTypeDesc;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public CodeType() {
	}

	public CodeType(String codeTypeName, String codeTypeShortDesc) {
		this.codeTypeName = codeTypeName;
		this.codeTypeShortDesc = codeTypeShortDesc;
	}

	public CodeType(String codeTypeName, String codeTypeShortDesc,
			String codeTypeDesc, Date lastUpdated, String lastUpdatedBy,
			Set codes) {
		this.codeTypeName = codeTypeName;
		this.codeTypeShortDesc = codeTypeShortDesc;
		this.codeTypeDesc = codeTypeDesc;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CODE_TYPE_ID", unique = true, nullable = false)
	public Integer getCodeTypeId() {
		return this.codeTypeId;
	}

	public void setCodeTypeId(Integer codeTypeId) {
		this.codeTypeId = codeTypeId;
	}

	@Column(name = "CODE_TYPE_NAME", nullable = false, length = 4)
	public String getCodeTypeName() {
		return this.codeTypeName;
	}

	public void setCodeTypeName(String codeTypeName) {
		this.codeTypeName = codeTypeName;
	}

	@Column(name = "CODE_TYPE_SHORT_DESC", nullable = false, length = 10)
	public String getCodeTypeShortDesc() {
		return this.codeTypeShortDesc;
	}

	public void setCodeTypeShortDesc(String codeTypeShortDesc) {
		this.codeTypeShortDesc = codeTypeShortDesc;
	}

	@Column(name = "CODE_TYPE_DESC", length = 45)
	public String getCodeTypeDesc() {
		return this.codeTypeDesc;
	}

	public void setCodeTypeDesc(String codeTypeDesc) {
		this.codeTypeDesc = codeTypeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}


}
