package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Institute generated by hbm2java
 */
@Entity
@Table(name = "institute", catalog = "reunited")
public class Institute implements java.io.Serializable {

	private Integer instituteId;
	private String instituteName;
	private Date lastUpdated;
	private String lastUpdatedBy;
	private Set<Branch> branches = new HashSet<Branch>(0);

	public Institute() {
	}

	public Institute(String instituteName) {
		this.instituteName = instituteName;
	}

	public Institute(String instituteName, Date lastUpdated,
			String lastUpdatedBy, Set branches) {
		this.instituteName = instituteName;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
		this.branches = branches;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INSTITUTE_ID", unique = true, nullable = false)
	public Integer getInstituteId() {
		return this.instituteId;
	}

	public void setInstituteId(Integer instituteId) {
		this.instituteId = instituteId;
	}

	@Column(name = "INSTITUTE_NAME", nullable = false, length = 50)
	public String getInstituteName() {
		return this.instituteName;
	}

	public void setInstituteName(String instituteName) {
		this.instituteName = instituteName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<Branch> getBranches() {
		return this.branches;
	}

	public void setBranches(Set<Branch> branches) {
		this.branches = branches;
	}

}
