package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RelationSessionStudent generated by hbm2java
 */
@Entity
@Table(name = "relation_session_student", catalog = "reunited")
public class RelationSessionStudent implements java.io.Serializable {

	private Integer relationSsId;
	private Session session;
	private User user;
	private Integer relationSsRollNo;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public RelationSessionStudent() {
	}

	public RelationSessionStudent(Session session, User user) {
		this.session = session;
		this.user = user;
	}

	public RelationSessionStudent(Session session, User user,
			Integer relationSsRollNo, Date lastUpdated, String lastUpdatedBy) {
		this.session = session;
		this.user = user;
		this.relationSsRollNo = relationSsRollNo;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RELATION_SS_ID", unique = true, nullable = false)
	public Integer getRelationSsId() {
		return this.relationSsId;
	}

	public void setRelationSsId(Integer relationSsId) {
		this.relationSsId = relationSsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RELATION_SS_SESSION_ID", nullable = false)
	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RELATION_SS_STUDENT_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "RELATION_SS_ROLL_NO")
	public Integer getRelationSsRollNo() {
		return this.relationSsRollNo;
	}

	public void setRelationSsRollNo(Integer relationSsRollNo) {
		this.relationSsRollNo = relationSsRollNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
