package com.reunited.entities;
// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name="session"
    ,catalog="reunited"
)
public class Session  implements java.io.Serializable {


     private Integer sessionId;
     private Class className;
     private Code code;
     private User user;
     private String sessionYear;
     private String sessionName;
     private String sessionClassRoomNumber;
     private Date lastUpdated;
     private String lastUpdatedBy;

    public Session() {
    }

	
    public Session(Class className, String sessionYear) {
        this.className = className;
        this.sessionYear = sessionYear;
    }
    public Session(Class className, Code code, User user, String sessionYear, String sessionName, String sessionClassRoomNumber, Date lastUpdated, String lastUpdatedBy, Set tests, Set timetables, Set relationSessionStudents) {
       this.className = className;
       this.code = code;
       this.user = user;
       this.sessionYear = sessionYear;
       this.sessionName = sessionName;
       this.sessionClassRoomNumber = sessionClassRoomNumber;
       this.lastUpdated = lastUpdated;
       this.lastUpdatedBy = lastUpdatedBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SESSION_ID", unique=true, nullable=false)
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SESSION_CLASS_ID", nullable=false)
    public Class getClassName() {
        return this.className;
    }
    
    public void setClassName(Class className) {
        this.className = className;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SESSION_STREAM_TYPE")
    public Code getCode() {
        return this.code;
    }
    
    public void setCode(Code code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SESSION_CLASS_TEACHER_ID")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="SESSION_YEAR", nullable=false, length=4)
    public String getSessionYear() {
        return this.sessionYear;
    }
    
    public void setSessionYear(String sessionYear) {
        this.sessionYear = sessionYear;
    }

    
    @Column(name="SESSION_NAME", length=10)
    public String getSessionName() {
        return this.sessionName;
    }
    
    public void setSessionName(String sessionName) {
        this.sessionName = sessionName;
    }

    
    @Column(name="SESSION_CLASS_ROOM_NUMBER", length=10)
    public String getSessionClassRoomNumber() {
        return this.sessionClassRoomNumber;
    }
    
    public void setSessionClassRoomNumber(String sessionClassRoomNumber) {
        this.sessionClassRoomNumber = sessionClassRoomNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    
    @Column(name="LAST_UPDATED_BY", length=45)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }






}


