package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemVariables generated by hbm2java
 */
@Entity
@Table(name = "system_variables", catalog = "reunited")
public class SystemVariables implements java.io.Serializable {

	private Integer systemId;
	private String systemCurrentSessionYear;

	public SystemVariables() {
	}

	public SystemVariables(String systemCurrentSessionYear) {
		this.systemCurrentSessionYear = systemCurrentSessionYear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SYSTEM_ID", unique = true, nullable = false)
	public Integer getSystemId() {
		return this.systemId;
	}

	public void setSystemId(Integer systemId) {
		this.systemId = systemId;
	}

	@Column(name = "SYSTEM_CURRENT_SESSION_YEAR", nullable = false, length = 4)
	public String getSystemCurrentSessionYear() {
		return this.systemCurrentSessionYear;
	}

	public void setSystemCurrentSessionYear(String systemCurrentSessionYear) {
		this.systemCurrentSessionYear = systemCurrentSessionYear;
	}

}
