package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestResult generated by hbm2java
 */
@Entity
@Table(name = "test_result", catalog = "reunited")
public class TestResult implements java.io.Serializable {

	private Integer testResultId;
	private Test test;
	private User user;
	private int testResultMarksObtained;
	private String testResultRemarks;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public TestResult() {
	}

	public TestResult(Test test, User user, int testResultMarksObtained) {
		this.test = test;
		this.user = user;
		this.testResultMarksObtained = testResultMarksObtained;
	}

	public TestResult(Test test, User user, int testResultMarksObtained,
			String testResultRemarks, Date lastUpdated, String lastUpdatedBy) {
		this.test = test;
		this.user = user;
		this.testResultMarksObtained = testResultMarksObtained;
		this.testResultRemarks = testResultRemarks;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TEST_RESULT_ID", unique = true, nullable = false)
	public Integer getTestResultId() {
		return this.testResultId;
	}

	public void setTestResultId(Integer testResultId) {
		this.testResultId = testResultId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_RESULT_TEST_ID", nullable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_RESULT_STUDENT_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "TEST_RESULT_MARKS_OBTAINED", nullable = false)
	public int getTestResultMarksObtained() {
		return this.testResultMarksObtained;
	}

	public void setTestResultMarksObtained(int testResultMarksObtained) {
		this.testResultMarksObtained = testResultMarksObtained;
	}

	@Column(name = "TEST_RESULT_REMARKS", length = 45)
	public String getTestResultRemarks() {
		return this.testResultRemarks;
	}

	public void setTestResultRemarks(String testResultRemarks) {
		this.testResultRemarks = testResultRemarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
