package com.reunited.entities;

// Generated May 26, 2015 3:56:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPinHistory generated by hbm2java
 */
@Entity
@Table(name = "user_pin_history", catalog = "reunited")
public class UserPinHistory implements java.io.Serializable {

	private Integer userPinId;
	private User user;
	private String userPinNumber;
	private Integer userPinViolationCount;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public UserPinHistory() {
	}

	public UserPinHistory(User user, String userPinNumber) {
		this.user = user;
		this.userPinNumber = userPinNumber;
	}

	public UserPinHistory(User user, String userPinNumber,
			Integer userPinViolationCount, Date lastUpdated,
			String lastUpdatedBy) {
		this.user = user;
		this.userPinNumber = userPinNumber;
		this.userPinViolationCount = userPinViolationCount;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_PIN_ID", unique = true, nullable = false)
	public Integer getUserPinId() {
		return this.userPinId;
	}

	public void setUserPinId(Integer userPinId) {
		this.userPinId = userPinId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PIN_USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "USER_PIN_NUMBER", nullable = false, length = 256)
	public String getUserPinNumber() {
		return this.userPinNumber;
	}

	public void setUserPinNumber(String userPinNumber) {
		this.userPinNumber = userPinNumber;
	}

	@Column(name = "USER_PIN_VIOLATION_COUNT")
	public Integer getUserPinViolationCount() {
		return this.userPinViolationCount;
	}

	public void setUserPinViolationCount(Integer userPinViolationCount) {
		this.userPinViolationCount = userPinViolationCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "LAST_UPDATED_BY", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
